language: rust

matrix:
  include:
    - rust: 1.9.0
      os: linux
      dist: trusty
    - rust: 1.9.0
      os: osx
    - rust: 1.10.0
      os: linux
      dist: trusty
    - rust: 1.10.0
      os: osx
    - rust: 1.11.0
      os: linux
      dist: trusty
    - rust: 1.11.0
      os: osx
    - rust: stable
      os: linux
      dist: trusty
    - rust: stable
      os: osx
    - rust: beta
      os: linux
      dist: trusty
    - rust: beta
      os: osx
    - rust: nightly
      os: linux
      dist: trusty
    - rust: nightly
      os: osx
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  directories:
    - llvm-3.9.0

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libdw-dev
      - libdw1
      - libelf-dev

env:
  global:
    secure: hveXyFhx/C/kWJebjAauSYBrOGMX8qpzXmWGCMBaeAtbXo2uGWs/a+VA/R/AfJS+EZv5e578ZVtcO773XDCryQ7j+nFJQGQWO/3pY00HqDnItwPmy6tp2BIlxtahAaYCufGJnm4yPtMFXajDvtp3n1oFCZvT+rINBelKb/9NggHyvnm9dz/0Hfj/2floyRRdC656jgOVpE/3bmi5N9UamZjHOvdP2ZVabKFgCacw2GKVQM3BFyKeKHpUy/n1lZtpKw4TMGLcw0Ot3VR/EobtR647MldM9kVZCHfdmAuJDGG2azdLyjm1OqSZZzyJH+IWhWzbXIXNhON7pwg39sLr1S1q5Gwf/OsEnRtov5CrnYdnEFeSZzU5i6uJ5hujU1KooppSHh/q08ELNzbTsYrug2OVtbGxrxUyU38rlZEI7iOCE+KIx3IDHWz3UOBebjArc3MDgB3LBi37pUqgfaMG265y7uH6LG5EfjperYX7IVtAcpZbIl2MQYXOz0UzU/jnPuqUlvKR1IHqMguPnt1V0w+SNUV4eG1PlhMsVnSxVDtCMfN18V6/yNL0xf0yFaxfesa3pluA3NfaPPTi1lcdXSifLZz6j1QGjHY1Sr6TpPKORwDQZoDY2b3tz5GAYbDIXPDeg2QmHWl2yPmI6AKMog6KGbLi2XKV30e7SidHHNI=

notifications:
  irc: "chat.freenode.net#taguavm"

install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          if [[ ! -n "$(ls -A llvm-3.9.0)" ]]; then
              curl 'http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz' --verbose > llvm-3.9.0.tar.xz;
              mkdir llvm-3.9.0;
              tar -xvf llvm-3.9.0.tar.xz --strip 1 -C llvm-3.9.0;
          fi

          export PATH="$PWD/llvm-3.9.0/bin/:$PATH";

          # llvm-config gives compiler arguments for the compiler it was
          # compiled with. On Ubuntu cc is gcc, so override that to avoid:
          # “unrecognized command line option ‘-Wcovered-switch-default’”.
          cc --version;
          sudo rm $(which cc);
          sudo ln -s $PWD/llvm-3.9.0/bin/clang /usr/bin/cc;
          cc --version;
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update;
          brew rm -f llvm;
          brew install llvm;
          export CXX="clang++ -stdlib=libc++"
          export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/llvm/include"
          export LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          export PATH="/usr/local/opt/llvm/bin:$PATH";
      fi
  - llvm-config --version

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH="$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH"

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only stable doc

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          travis-cargo --only stable doc-upload;
          travis-cargo coveralls --no-sudo;
      fi
